framework:
    workflows:
        comment:
            type: state_machine
            marking_store:
                type: method
                property: state
            supports:
                - App\Entity\Comment
            initial_marking: submitted
            places:
                - submitted
                - ham
                - potential_spam
                - spam
                - rejected
                - ready
                - published
            transitions:
                accept:
                    from: submitted
                    to: ham
                might_be_spam:
                    from: submitted
                    to: potential_spam
                reject_spam:
                    from: submitted
                    to: spam
                publish_ham:
                    from: ham
                    to: ready
                reject_ham:
                    from: ham
                    to: rejected
                publish:
                    from: potential_spam
                    to: ready
                reject:
                    from: potential_spam
                    to: rejected
                optimize:
                    from: ready
                    to: published
